package com.omlah.customer.service;


public enum RequestID {

    //GET STARTING

    REQ_NUMBER_CHECK,
    REQ_EMAIL_CHECK,
    REQ_LOGIN,
    REQ_LOGOUT,
    REQ_SIGNUP,
    REQ_COUNTRYLIST,

    REQ_GET_RECEIVER_DETAILS,
    REQ_BENEFICIARY_LIST,
    REQ_ADD_BENEFICIARY,
    REQ_DELETE_BENEFICIARY,

    REQ_USER_PROFILE,

    REQ_MERCHANT_LIST,
    REQ_SELLER_LIST,

    REQ_AMOUNT_TAX,
    REQ_PAYMONEY,
    REQ_REQEST_MONEY,
    REQ_MONEYREQUEST_LIST,
    REQ_MONEYREQUEST_REJECT,
    REQ_STATUS_UPDATE,

    REQ_TRANSACTION_LIST,
    REQ_TRANSACTION_DEATILS,
    REQ_POPCOINS_LIST,
    REQ_SEND_COINS,

    REQ_QR_DETAILS,
    REQ_CUSTOMER_QR_DETAILS,
    REQ_SCAN_AND_PAY,

    REQ_FEED,
    REQ_FEED_HIDE,

    REQ_EVENT_LIST,
    REQ_EVENT_DETAILS,
    REQ_EVENT_BOOKING,
    REQ_BOOKING_DETAILS,
    REQ_BOOKING_EVENT_LIST,

    REQ_PROFILE_IMAGE_IPLOAD,
    REQ_CURRENCY_CONVERSION,


    REQ_RESEND_OTP,
    REQ_VERIFY_OTP,
    REQ_ADD_PASSCODE,
    REQ_VERIFY_PASSCODE,

    REQ_ADD_BANK_ACCOUNT,
    REQ_BANK_LIST,
    REQ_WITHDRAW_AMOUNT,
    REQ_WITHDRAW_LIST,

    REQ_FORGET_PASSWORD,
    REQ_SET_NEW_PASSWORD,
    REQ_CHANGE_PASSWORD,


    REQ_OFFER_LIST,
    REQ_CARD_LIST,
    REQ_LOAD_MONEY,
    REQ_CARD_DELETE,
    REQ_REFER_HISTORY,
    REQ_ADD_CARD,

    GET_REWARD_LIST,
    GET_REWARD_DETAILS,


    REQ_GET_PROVIDERS,
    REQ_POST_RECHARGE,
    REQ_GET_RECHARGE_HISTORY,

    REQ_GET_PROMOTION,
    REQ_VOCUHER_DETAILS,
    REQ_VOCUHER_CODE,
    REQ_GET_TRADINGS,
    REQ_REDEEM_POINTS,
    REQ_MY_VOUCHERCODE,

    REQ_AUTO_FETCH,
    REQ_GET_OPERATOR,
    REQ_OPERATOR_DETAILS,
    REQ_COMPLETE_RECHARGE

}
